trigger:

  branches:
    include:
      - main   # Change this if your default branch is different

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'Azure Subscription 1(ac75e7f3-86b0-4143-9794-ea30c388af3d)'  # Replace with your Azure Service Connection name
  webAppName: 'app1web'                # Replace with your web app name
  webAppNameDev: 'app1devweb'
  artifactName: 'drop'

stages:
- stage: Build
  displayName: 'Build .NET WebApp'
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '8.0.x'  # Use your required .NET version

    - task: DotNetCoreCLI@2
      displayName: 'Restore dependencies'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: 'Build project'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'Publish project'
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: $(artifactName)

- stage: Deploy2Dev
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - deployment: DeployWeb2Dev
    environment: 'development'  # or create an environment name you prefer
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppNameDev)
              package: '$(Pipeline.Workspace)/$(artifactName)/*.zip'

- stage: Deploy2Prod
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  jobs:
  - deployment: DeployWeb2Prod
    environment: 'production'  # or create an environment name you prefer
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: $(artifactName)

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure App Service'
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/$(artifactName)/*.zip'
